server:
  port: 8081

app:
  base-url: http://localhost:8081

spring:
  datasource:
    url: jdbc:mysql://xefi550t7t6tjn36.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/wx382dz6idjpa7lz
    username: rxwkd0u12nqen6xx
    password: y0ya52m8umu8p2yz
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

  mailServer:
    host: smtp.gmail.com
    port: 587
    email: qkgamming@gmail.com
    password: trel ebon hzes wpmc
    protocol: smtp
    isSSL: false



signer:
  key: MRkporsIItbA8Bvv4yisUmzXgt3xKsPSm4/v+Qg86TIwVyi4olnKNczsadze6e85
